### ISSUE TITLE
How to build CSS in separate file

### ISSUE THREAD

**Issue by davinkevin** [brillout/gulp-jspm#11]
Hi, 

I have tryed, on a seed project to add gulp-jspm to my build, but with no luck.

I want to do the same thing as the following command on this project (https://github.com/davinkevin/angularjs-jspm-seed)  : 
```shell
jspm bundle-sfx app.js dist/app.js
```

But, I have some specific plugin (like css and text). In case of CSS, i would like to use the options to build with a separate CSS (better for production, the rendering is instantaneous.

If I use this task, no css output : 
```js
gulp.task('build', function(){
  return gulp.src('public/app.js')
    .pipe(jspmb({
      selfExecutingBundle: true
    }))
    .pipe(gulp.dest('dist/'));
});
```

If I add plugin support (with plugin : css) like this : 
```js
gulp.task('build', function(){
  return gulp.src('public/app.js')
    .pipe(jspmb({
      selfExecutingBundle: true,
      inject : true,
      plugin : 'css',
      buildCSS : true,
      separateCSS: true
    }))
    .pipe(gulp.dest('dist/'));
});
```
The output is only a file with the SystemJS element / polyfill in it...

And if I set the plugin to true, I have the following error : 
```
Unhandled rejection Error: ENOENT, open '/Users/kdavin/Workspace/GitHub/angularjs-jspm-seed/public/js.js'
    at Error (native)
From previous event:
    at processImmediate [as _immediateCallback] (timers.js:358:17)
From previous event:
    at DestroyableTransform._transform (/Users/kdavin/Workspace/GitHub/angularjs-jspm-seed/node_modules/gulp-jspm/index.js:40:10)
    at DestroyableTransform.Transform._read (/Users/kdavin/Workspace/GitHub/angularjs-jspm-seed/node_modules/gulp-jspm/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (/Users/kdavin/Workspace/GitHub/angularjs-jspm-seed/node_modules/gulp-jspm/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:160:12)
    at doWrite (/Users/kdavin/Workspace/GitHub/angularjs-jspm-seed/node_modules/gulp-jspm/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:326:12)
    at writeOrBuffer (/Users/kdavin/Workspace/GitHub/angularjs-jspm-seed/node_modules/gulp-jspm/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:312:5)
    at DestroyableTransform.Writable.write (/Users/kdavin/Workspace/GitHub/angularjs-jspm-seed/node_modules/gulp-jspm/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:239:11)
    at write (/Users/kdavin/Workspace/GitHub/angularjs-jspm-seed/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/kdavin/Workspace/GitHub/angularjs-jspm-seed/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/Users/kdavin/Workspace/GitHub/angularjs-jspm-seed/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at DestroyableTransform.emit (events.js:104:17)
    at emitReadable_ (/Users/kdavin/Workspace/GitHub/angularjs-jspm-seed/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/Users/kdavin/Workspace/GitHub/angularjs-jspm-seed/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk (/Users/kdavin/Workspace/GitHub/angularjs-jspm-seed/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
    at DestroyableTransform.Readable.push (/Users/kdavin/Workspace/GitHub/angularjs-jspm-seed/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)
    at DestroyableTransform.Transform.push (/Users/kdavin/Workspace/GitHub/angularjs-jspm-seed/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:145:32)
    at afterTransform (/Users/kdavin/Workspace/GitHub/angularjs-jspm-seed/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:101:12)
    at TransformState.afterTransform (/Users/kdavin/Workspace/GitHub/angularjs-jspm-seed/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at DestroyableTransform.noop [as _transform] (/Users/kdavin/Workspace/GitHub/angularjs-jspm-seed/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/through2.js:26:3)
    at DestroyableTransform.Transform._read (/Users/kdavin/Workspace/GitHub/angularjs-jspm-seed/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
```

I think I miss something, but I don't know what... Could you help ?

**Comment by brillout** [comment]
how about;
 - don't import the css in your js files
 - have another gulp task to compile the css

would that work for you?

**Comment by davinkevin** [comment]
I use some SystemJS plug-in to have dependency for css / html template.

The goal for us when using SystemJS is to let SystemJS handle all the import needed... so we don't have to handle it manually.

You can see our example for the template (https://github.com/davinkevin/angularjs-jspm-seed/blob/master/public/messages/messages.js#L3) and for the CSS (https://github.com/davinkevin/angularjs-jspm-seed/blob/master/public/config/bootstrap/bootstrap.js).

With this logic, we handle all our dependency in the same spot, so we can see all a module need to be executed...

By this usage, JSPM is very powerful and can compete with webpack for example.

**Comment by brillout** [comment]
Ok makes sense.

I'm not aware of a way to do that with JSPM.

I would open an Issue at https://github.com/jspm/jspm-cli though

**Comment by tniswong** [comment]
@brillout is right. Keep your JS and CSS separate. Consider using LESS/SASS for bundling styles.

**Comment by telekosmos** [comment]
JS and CSS are separated, instead you use html markup to load the CSS, you load them in the main app file using system.js. It is true jspm can't manage CSS preprocessors, you'd have to have a previous build step before bundling. Can be a matter of taste, but I prefer to load those dependencies through jspm/systemjs. 

In addition, jspm uses [https://github.com/systemjs/plugin-css](plugin-css) to load and bundle the css, but so far there is [https://github.com/systemjs/plugin-css/issues/61](this issue) which sometimes can make the bundle unsuccessful.

**Comment by davinkevin** [comment]
@tniswong : We are using pre-processors, but it's simpler to use JSPM to add some files to our build. 

Like I said, some lib needs to have JS and CSS to works... why handling two system of dependency (one for the JS part (with 'import' in JS) and another for injecting the CSS in html markup... 

For information, in production, we have one large CSS files with all the css required / imported by our JSPM build (with the option Separate CSS).

With JSPM and his plugin logic, we can handle a lot of assets (https://github.com/systemjs/systemjs#plugins), and JSPM / SystemJS give us some API to use it in memory during our build (see https://github.com/systemjs/builder/issues/365).

**Comment by brillout** [comment]
@davinkevin have you talked with jspm maintainers about that?

closing, since this is not related to gulp-jspm

**Comment by davinkevin** [comment]
Yeah, I talked with the core maintener of JSPM, and this is handle by the system. The plugin 'css' allow to do that very simply. For example I use it here (https://github.com/davinkevin/angularjs-jspm-seed/blob/master/build/tasks/build.js#L22) with the default JSPM builder.
