### ISSUE TITLE
Can't run demo successfully

### ISSUE THREAD

**Issue by tachun** [brillout/gulp-jspm#2]
Hello @brillout,

Thanks for this demo, but I got some errors when I tried to run `gulp`, it say it can't find gulp-util, but I don't see any `gulp-util` in package.json, do u have any idea of this ?

```module.js:338
    throw err;
          ^
Error: Cannot find module 'gulp-util'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/tachun/code/open-source/gulp-jspm/index.js:1:75)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by brillout** [comment]
Hello @tachun,

You are welcome.
`npm install` has to be run twice; once for the gulp-jspm plugin itself and once for the demo.

The steps to run are;
```shell
git clone git@github.com:brillout/gulp-jspm
cd gulp-jspm/
npm install # once for the plugin 
cd demo/
npm install # once for the demo
npm install -g gulp
gulp
gulp sourcemap
gulp test
```

The readme was wrong and I just corrected it.

Thanks!

**Comment by tachun** [comment]
Hello @brillout,
Thank for reply, it works perfectly :)
