### ISSUE TITLE
Support jspm v0.17?

### ISSUE THREAD

**Issue by heroandtn3** [brillout/gulp-jspm#25]
jspm 0.17 beta is out for a while, I tried it today I got this:

```
Unhandled rejection TypeError: jspm.bundleSFX is now jspm.build
    at EventEmitter.API.bundleSFX (node_modules/jspm/api.js:116:25)
    at Promise.resolve.then.then.spread.then.results.temp_path (node_modules/gulp-jspm/index.js:42:68)
```

My gulp task configuration:

```JavaScript
gulp.task('js', function () {
  gulp.src(['client/js/main.js'])
    .pipe(jspm({ selfExecutingBundle: true }))
    .pipe(gulp.dest('build/js/'));
});
```

**Comment by frederikschubert** [comment]
I think the only change that is necessary would be to change [this](https://github.com/brillout/gulp-jspm/blob/master/index.js#L42) line. `bundleSFX` should simply be changed to `build`.
I would also like to use this plugin with jspm 0.17 as it brings many improvements.

**Comment by brillout** [comment]
up to do a PR? :)

**Comment by heroandtn3** [comment]
@brillout I think things are not simple like that, `gulp-jspm` is using its own `jspm` package to do the job but not the `jspm` package of the node application. This is not nice because we cannot support both JSPM 0.16 and 0.17 in the same time.

**Comment by brillout** [comment]
@heroandtn3 how about a beta version for gulp-jspm? beta gulp-jspm -> beta jspm, stable gulp-spm -> stable jspm

API changes that aren't backward compatible are a problem when using the jspm package of the application

**Comment by frederikschubert** [comment]
Sorry I have been traveling the last months and forgot to reply. The beta approach sounds good!
