### ISSUE TITLE
TypeError: Cannot read property 'bundles' of null

### ISSUE THREAD

**Issue by Sri276286** [brillout/gulp-jspm#42]
Hi,

I am getting this error : 

events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'bundles' of null
  at buildConfig (C:\Demos\bundling ex\my-project\node_modules\gulp-jspm-build\lib\buildConfig.js:5:15)
  at C:\Demos\bundling ex\my-project\node_modules\gulp-jspm-build\lib\build.js:41:30
  at process._tickCallback (internal/process/next_tick.js:103:7)
  at Module.runMain (module.js:606:11)
  at run (bootstrap_node.js:394:7)
  at startup (bootstrap_node.js:149:9)
  at bootstrap_node.js:509:3

**Comment by brillout** [comment]
I don't maintain `gulp-jspm` anymore, see [issue #45 - Looking for a maintainer / fork](https://github.com/brillout/gulp-jspm/issues/45).

Thanks for creating the issue.
