### ISSUE TITLE
gulp-jspm fails on windows

### ISSUE THREAD

**Issue by gscoppino** [brillout/gulp-jspm#8]
This can be reproduced in the demo as well, clone the repo and follow the instructions in the README. Once you run ```gulp```, it will fail. Manually bundling from the command line using jspm works.

```
Unhandled rejection Error: Unable to calculate canonical name to bundle C://\Users\scopp\Sandbox\gulp-jspm\demo\src\main.js
    at getCanonicalNamePlain (C:\Users\scopp\Sandbox\gulp-jspm\node_modules\jspm\node_modules\systemjs-builder\lib\utils.js:177:13)
    at getCanonicalName (C:\Users\scopp\Sandbox\gulp-jspm\node_modules\jspm\node_modules\systemjs-builder\lib\utils.js:88:19)
    at C:\Users\scopp\Sandbox\gulp-jspm\node_modules\jspm\node_modules\systemjs-builder\lib\arithmetic.js:84:38
    at runMicrotasksCallback (node.js:337:7)
    at process._tickCallback (node.js:355:11)
From previous event:
    at processImmediate [as _immediateCallback] (timers.js:367:17)
From previous event:
    at DestroyableTransform._transform (C:\Users\scopp\Sandbox\gulp-jspm\index.js:40:10)
    at DestroyableTransform.Transform._read (C:\Users\scopp\Sandbox\gulp-jspm\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (C:\Users\scopp\Sandbox\gulp-jspm\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:160:12)
    at doWrite (C:\Users\scopp\Sandbox\gulp-jspm\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:326:12)
    at writeOrBuffer (C:\Users\scopp\Sandbox\gulp-jspm\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:312:5)
    at DestroyableTransform.Writable.write (C:\Users\scopp\Sandbox\gulp-jspm\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:239:11)
    at write (C:\Users\scopp\Sandbox\gulp-jspm\demo\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:623:24)
    at flow (C:\Users\scopp\Sandbox\gulp-jspm\demo\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (C:\Users\scopp\Sandbox\gulp-jspm\demo\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:664:5)
    at DestroyableTransform.emit (events.js:104:17)
    at emitReadable_ (C:\Users\scopp\Sandbox\gulp-jspm\demo\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:448:10)
    at emitReadable (C:\Users\scopp\Sandbox\gulp-jspm\demo\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:444:5)
    at readableAddChunk (C:\Users\scopp\Sandbox\gulp-jspm\demo\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:187:9)
    at DestroyableTransform.Readable.push (C:\Users\scopp\Sandbox\gulp-jspm\demo\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:149:10)
    at DestroyableTransform.Transform.push (C:\Users\scopp\Sandbox\gulp-jspm\demo\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:145:32)
    at afterTransform (C:\Users\scopp\Sandbox\gulp-jspm\demo\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:101:12)
    at TransformState.afterTransform (C:\Users\scopp\Sandbox\gulp-jspm\demo\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:79:12)
    at DestroyableTransform.noop [as _transform] (C:\Users\scopp\Sandbox\gulp-jspm\demo\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\through2.js:26:3)
    at DestroyableTransform.Transform._read (C:\Users\scopp\Sandbox\gulp-jspm\demo\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:184:10)
```

On a side note, the README does not mention that you also need to run ```jspm install``` in the demo folder, after ```npm install```. Otherwise you won't be able to build the demo from the command line either.

**Comment by brillout** [comment]
thanks for opening this issue.

This could be because you are running gulp-jspm on windows, I haven't tried gulp-jspm with windows (yet).

Do you maybe have a unix machine on which you could reproduce the error?
I don't have any machine with windows at the moment.

**Comment by brillout** [comment]
Because there are no dependencies other than SystemJS the demo works without `jspm install`.
But to avoid confusion I've added `jspm install` to the instructions.

**Comment by gscoppino** [comment]
I did attempt this on a Windows machine. On an Ubuntu 14.04 box there were no problems, so it definitely seems to be a Windows-specific issue.

**Comment by larserikfinholt** [comment]
I've got the same problem on a windows machine. 
As a workaround to others I ended up with a simple exec task like this:


    var exec = require('child_process').exec;

    gulp.task('jspmBuild', function (cb) {
            exec('jspm bundle src/app/app.js dist/app.min.js', function (err, stdout, stderr) {
                cb(err);
            });
     });

**Comment by brillout** [comment]
thanks for the input and the workaround.

I will check that once I have time to find a way to install windows on a VM without needing to pay any license.

**Comment by tniswong** [comment]
+1. Can confirm that I also get this error on Windows.

This is my workaround, similar approach as above, just using jspm directly.

```javascript
import jspm from 'jspm';

gulp.task('bundle:js', (done) => {

    jspm.bundleSFX(paths.src.js(entryPoint.js), paths.work.js('bundle.js'), {
        minify: true
    })
    .then(done)
    .catch(done);

});
```

I also did a small bit of digging into causes. I believe that this issue is related to how Gulp and Vinyl preserve path names from globs, then pass them into jspm. On linux/macs this is fine because they use the same file path style. Windows is different because of the backslashes. You can see this in the error message above: `C://\Users\scopp\Sandbox\gulp-jspm\demo\src\main.js`

I believe that the vinyl paths need to be path.normalized or something before they are sent into jspm.

Hope that helps.

**Comment by brillout** [comment]
Apparently #12 fixes this issue
